default: &default
  encoding: utf8
  adapter: postgresql
  min_messages: warning
  pool: <%= [Integer(ENV.fetch("MAX_THREADS", 5)), Integer(ENV.fetch("DB_POOL", 5))].max %>
  timeout: 5000
  username: <%= ENV.fetch("QID_LOOKUP_DB_SUPER_USERNAME", "") %>
  url:  <%= ENV.fetch("QID_LOOKUP_DATABASE_URL", "") %>

development:
  <<: *default
  url:  <%= ENV.fetch("QID_LOOKUP_DATABASE_URL", "") %>

test:
  <<: *default
  database: ot_test

production:
  <<: *default
  url:  <%= ENV.fetch("QID_LOOKUP_DATABASE_URL", "") %>

